### ISSUE TITLE
publish a new version

### ISSUE THREAD

**Issue by noamokman** [vweevers/node-in-production#1]
Hey,
Looks like the `package.json` on github lists `envify` as a dev dependency.
But the published version has it as a dependency.

Can you publish a new version?

**Comment by vweevers** [comment]
It should be a `dependency`, actually. Otherwise browserify builds break (if you don't already have `envify` somewhere in `node_modules`).

So `envify` being a `devDependency` is a bug. I'll open an issue. I don't use this module anymore (it's modularity gone too far), but will gladly accept a PR.

@noamokman I think you're asking for the opposite, so I recommend just inlining the one-liner (`process.env.NODE_ENV === 'production'`).

**Comment by noamokman** [comment]
Actually, it's pretty weird to add a dependency if the code doesn't use it.
Maybe the docs should just say that if you want to use it with browsrify you need to add it yourself. 
I have used this with webpack before and it worked great. 
If you don't want to, I'll just replace my code with the one line.
Thanks anyway 😊

**Comment by vweevers** [comment]
> Actually, it's pretty weird to add a dependency if the code doesn't use it.

The code doesn't use it, but browserify does. Including such a dependency is common practice, and really isn't a problem.
